name: Mirror to Gitee Repo

on: [ push ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    if: github.repository == 'Baichuan-Sihai/Fluidity'  # repo to be synced
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }} # ssh private key stored in the repository Fluidity => Settings => Secrets and variables => Actions => GITEE_PRIVATE_KEY, both Github and Gitee should add to same public key matching this private key
        with:
          source-repo: "git@github.com:Baichuan-Sihai/Fluidity.git"
          destination-repo: "git@gitee.com:baichuansihai/Fluidity.git"
